name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Check format, types and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      # ignore scripts as indy-sdk will try to build and we don't have libindy
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Check prettier
        run: yarn check-format

      - name: Check types
        run: yarn check-types

      - name: Test build website
        run: yarn build
